[workspace]
members = [
    "callback-server",
    "sonos-discovery",
    "sonos-stream",
    "soap-client",
    "sonos-api",
    "test-av-transport",
    "test-rendering-control",
    "debug-soap",
]
resolver = "2"
