[workspace]
members = [
    "callback-server",
    # "integration-example",  # Temporarily disabled while refactoring UPnP client
    "sonos-discovery",
    "sonos-stream",
    "soap-client",
    "sonos-api",
]
resolver = "2"
