[package]
name = "callback-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
bytes = "1.0"

[dev-dependencies]
reqwest = "0.11"
